### ISSUE TITLE
No example of solution

### ISSUE THREAD

**Issue by feiandytan** [MicrosoftDocs/visualstudio-docs.zh-cn#129]
This page doesn't have example of how to fix the violation.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7193fffc-ff49-d551-417e-6f004dd1e216
* Version Independent ID: 8370a61d-8d8a-bec4-b49d-e5cae67a0d86
* Content: [CA2213:应释放可释放的字段 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2213-disposable-fields-should-be-disposed.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/code-quality/ca2213-disposable-fields-should-be-disposed.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hello, @fei

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/3550

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
