### ISSUE TITLE
Is this function "generating map" fit for linux project?

### ISSUE THREAD

**Issue by yuqingyang888** [MicrosoftDocs/visualstudio-docs.zh-cn#162]
Is this function "generating map" fit for linux project?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8e2a9062-ef1a-b4fb-c76c-2a284f2ccb93
* Version Independent ID: 26525968-81c9-f00c-c270-276245099ddd
* Content: [查看源文件和C++标头文件之间的依赖关系 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/modeling/code-maps-for-cpp?view=vs-2019#feedback)
* Content Source: [docs/modeling/code-maps-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/modeling/code-maps-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by srvbpigh** [comment]
Hello, @yuqingyang888
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4209](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4209) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @yuqingyang888

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4209

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
