### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zhengyang1220** [MicrosoftDocs/visualstudio-docs.zh-cn#177]
good

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9996cb85-f867-e5bf-3ac6-77971f45062e
* Version Independent ID: afefb77c-4530-0643-64fa-b99ceec93139
* Content: [在 Visual Studio 中使用数据 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/data-tools/accessing-data-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/data-tools/accessing-data-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/data-tools/accessing-data-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by srvbpigh** [comment]
Hello, @zhengyang1220
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @zhengyang1220 , 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 

We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 
Microsoft DOCS International Team
