### ISSUE TITLE
 ${repeated} does'nt work

### ISSUE THREAD

**Issue by fantasyhh** [MicrosoftDocs/visualstudio-docs.zh-cn#181]
Version:1.41.1
Commit:26076a
OS:Linux x64 4.15.0-88-generic

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [使用正则表达式 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @fantasyhh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5000](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5000) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @fantasyhh, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5000. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
