### ISSUE TITLE
The test code screenshot for NUnit is the code of MSTest

### ISSUE THREAD

**Issue by SCHQ** [MicrosoftDocs/visualstudio-docs.zh-cn#182]
The test code screenshot for NUnit is the code of MSTest

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 107f3c03-dac2-0226-d5c1-f2f49daa413d
* Version Independent ID: aaf80310-28eb-462b-d4f1-6b97a8abe260
* Content: [单元测试入门 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/test/getting-started-with-unit-testing?view=vs-2019#feedback)
* Content Source: [docs/test/getting-started-with-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/test/getting-started-with-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @SCHQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5078](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5078) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @SCHQ, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5078. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
