### ISSUE TITLE
FileTracker : error FTK1011. Probability appears when using windows clcache mechanism

### ISSUE THREAD

**Issue by yebanqingxing123** [MicrosoftDocs/visualstudio-docs.zh-cn#191]
FileTracker : error FTK1011: could not create the new file tracking log file: D:\SHARED_LIBRARIES\libc_sec\libc_sec.dir\Release\libc_sec.tlog\clcache_main-cl.read.1.tlog. The file exists. [D:\SHARED_LIBRARIES\libc_sec\libc_sec.vcxproj]

**Comment by srvbpigh** [comment]
Hello, @yebanqingxing123
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>, 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged. 

Please review issue https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/190  For this reason we are closing this issue since it is duplicated. 


Kind regards, 

Microsoft DOCS International Team
