### ISSUE TITLE
How to set up and verify PYTHONHOME settings?

### ISSUE THREAD

**Issue by GXY2017** [MicrosoftDocs/visualstudio-docs.zh-cn#196]
[在此处输入反馈]
I am stopped by  PYTHONHOME envar.  I installed the python in VS installer, not knowing how to make sure PYTHONHOME is set up.  There is not enough information provide about this point. 

Thank you.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [编写 Python 的 C++ 扩展 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @GXY2017
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5436](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5436) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @GXY2017 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5436

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
